### ISSUE TITLE
Clean up .re files from /tests for ReScript project

### ISSUE THREAD

**Issue by ajf-ajf** [tmattio/spin-rescript#1]
Super project, thanks for putting this together.

Quick issue report: using the template for a ReScript syntax project generates these errors when attempting to start or build a clean project:

```sh
Error: Invalid bsconfig.json implementation and interface have different path names or different cases tests/PageHome_test vs tests/PageHome_test
```

Deleting /tests/PageHome_test.re and /tests/support/Utils.re, leaving only the .res files for the tests in the same folders, fixes it. (I haven't checked what happens if Reason syntax is chosen.)

**Comment by tmattio** [comment]
Hey @ajf-ajf, thanks for opening the issue, I'll look into it 🙂

**Comment by ajf-ajf** [comment]
That'd be cool! I've been fluffing around with webpack and soooo many ReScript-related options for the past week or so, and, I don't actually think much of it matters in the end. It's nice to have a solid base to work with, and modify if/when necessary.

I haven't used Tailwind before (have built my own CSS modules instead), but this in `/config/tailwind.config.js` would get rid of the two warnings with each build:

```js
module.exports = {
  // ...
  future: {
    removeDeprecatedGapUtilities: true,
    purgeLayersByDefault: true,
  },
}
```

I (honestly) don't know if that's something you want to add too or not.

**Comment by tmattio** [comment]
@ajf-ajf This should be fixed, let me know if you have any other problem.

I didn't want to add these settings in the template because I don't want to update the template for every TailwindCSS release. Thanks for the suggestion though, don't hesitate if you see anything else that can be improved!

**Comment by ajf-ajf** [comment]
@tmattio -- Fair enough, re: tailwind, and thanks for the quick fix. It was already there when I went to try something else. :+1: 

The only other thing I've come across relevant to a base build is the package.json `start` scripts. Running bs build and webpack concurrently from clean causes webpack to error because there's no index.bs.js to load, then it runs again when bsb is finished doing its thing. If its not clean, then it picks up a stale index.bs.js and then reloads. Something like this might work:

```json
{
  // ...
  "start": "yarn bs:clean && yarn bs:build && concurrently -c --kill-others 'yarn bs:watch' 'yarn webpack:start'",
  "bs:build": "bsb -make-world",
  "bs:clean": "bsb -clean-world",
  "bs:watch": "bsb -make-world -w",
  "webpack:start": "webpack-dev-server --config config/webpack.config.js --open",
  // ...
}
```

But I don't want to tell you your thing... :-) This was super. Ta!

**Comment by tmattio** [comment]
Right! I pushed it in https://github.com/tmattio/spin-rescript/commit/168f931594184416f19ad59c20e37f88bceb0e9c, thanks for the suggestion @ajf-ajf 🙂

**Comment by ajf-ajf** [comment]
Cool, thanks!
